const preProcessing = {
    NOT_FOUND : '일치하는 정보가 없습니다.',
    MINIMUM6 : '최소 6글자 이상 만들어주세요.',
    NOT_CORRECT_FORM : '영어, 숫자, 특수기호를 모두 사용해주세요.',
    ENTER_EMAIL : '이메일을 입력해주세요 !',
    NOT_CORRECT_EMAIL : '올바른 이메일 형식을 입력해주세요 !',
    ENTER_VALUE : '값을 입력해주세요.',
    REQUIRED_AUTH_NUBER : '인증 번호를 입력해주세요.',
    ENTER_EMAIL : '이메일을 입력해주세요 !',
    WRONG_ACCESS : 'wrong access',
    ENTER_ID : 'ID를 입력해주세요.',
    USE_ENGNO : '영어와 숫자를 사용해주세요.',
    ISLOGIN : 'isLogin',
    AT_LEAST3 : '3글자 이상 입력해주세요',
    NO_SUBJECT : 'no subject',
    NO_CONTENT : 'no content',
    NO_IDEAIDX : 'no ideaIdx',
    EXIST_EMAIL : '이미 존재하는 이메일입니다.',
    FAIL_TO_SEND : 'fail to send',
    NOT_CORRECT_AUTHNO : '인증번호가 일치하지 않습니다!',
    WRONG_PW : '잘못된 비밀번호 입니다.',
    WRONG_ID : '잘못된 아이디 입니다.',
    TRAFFIC : '트래픽 문제로 잠시 후 다시 시도해주세요(이미 존재하는 회원)',
}

const postProcessing = {
    UNABLE_USERCOUNT : 'Unable to get userCount',
    UNABLE_TODAY_VISITOR : 'Unable to get todayVisitor',
    UNABLE_TOTAL_VISITOR : 'Unable to get totalVisitor',
    UNABLE_NEWITEMS : 'Unable to get newsItem',
    UNABLE_SIGNUP :' Unable signup',
    UNABLE_SEND_MAIL : 'Unable sendEmail',
    UNABLE_CHECK_MAIL : 'Unable to checkEmail',
    UNABLE_FIND_ID_SEND_MAIL : 'Unable to findIdSendMail',
    UNABLE_FIND_PW_SEND_MAIL :' Unable to findPwSendMail',
    UNABLE_UPDATE_PW  : 'Unable to updatePw',
    UNABLE_SIGNIN : 'Unable to signIn',
    UNABLE_CHECKID : 'Unable to checkId',
    UNABLE_CHECKNICKNAME : 'Unable to checkNickName',
    UNABLE_USERROLE : 'Unable to updateUserRole',
    UNABLE_GET_USER : 'Unable to getUser(role:admin)',
    UNABLE_LOGOUT : 'Unable to logout',
    UNABLE_FORCE_SIGNIN : 'Unable to forcesignIn',
    UNABLE_FIND_ID_USER : 'Unable to findIdUser',
    UNABLE_CREATEIP : 'Unable to create Ip',
    //comment,
    UNABLE_POST_COMMENT : 'Unable to postComment',
    UNABLE_GET_COMMENT : 'Unable to getComment',
    //idea
    UNABLE_POST_IDEA : 'Unable to postIdea',
    UNABLE_DELETE_IDEA : 'Unable to deleteIdea',
    UNABLE_UPDATE_IDEA : 'Unable to updateIdea',
    UNABLE_SHOW_IDEA : 'Unable to showIdea',
    UNABLE_SHOW_MY_IDEA : 'Unable to showMyIdea',
    UNABLE_SHOW_ADMIN_IDEA : 'Unable to showAdminUserIdea',
    UNABLE_CLICK_IDEA : 'Unable to getClickIdea',
    UNABLE_IDEA_COUNT : 'Unable to getIdeaCout',
    UNABLE_UPDATE_USERTOKEN : 'Middleware refresh : unable to updateUserToken',
    //middleware

}

const dbError = {
//anonymous
    DB_GET_USER_COUNT : 'Unable to getUserCount[service]',
    DB_GET_NEWS_ITEM : 'Unable to getNewsItem[service]',
    DB_SIGNUP : 'Unable to signUp[service]',
    DB_FIND_USER_PARA_ID : 'Unable to findUser(id) for sendMail[service]',
    DB_FIND_USER_PARA_EMAIL : 'Unable to findUser(email) for sendMail[service]',
    DB_SEND_EMAIL : 'Unable to sendMail[service]',
    DB_FIND_AUTH_NO : 'Unable to findAuthNo for checkEmail[service]',
    DB_CHECK_EMAIL : 'Unable to checkEmail[service]',
    DB_FIND_USER_FOR_FINDID : 'Unable to findUser for findIdSendMail[service]',
    DB_FIND_ID_SEND_MAIL : 'Unable to send findId [servcie]',
    DB_FIND_PW_SEND_MAIL : 'Unable to send findPw[service]',
    DB_UPDATE_PW : 'Unable to updatePw[service]',
    DB_FIND_ID_SIGNIN : 'Unable to findId for signIn[service]',
    DB_SIGNIN : 'Unable to signIn[service]',
    DB_DUPLICATE_ID : 'Unable to duplicatedId[service]',
    DB_DUPLICATE_NICKNAME : 'Unable to duplicatedNickName[service]',
    DB_MAKE_USER_TOKEN : "Unable to makeUserToken[service]",
    DB_HAVE_USER_TOKEN : "Unable to haveUserToken[service]",
    DB_SAVE_USER_TOKEN : "Unable to saveUserToken[service]",
    DB_FIND_USER_PARA_IDPW : 'Unable to findIdUser for forceSignIn[service]',
    //comment
    DB_POST_COMMENT : 'Unable to postComment[service]',
    DB_GET_COMMENT : 'Unable to getComment[service]',
    //idea
    DB_GET_IDEA_COUNT : 'Unable to getIdeaCount[service]',
    DB_CREATE_IDEA : 'Unable to createIdea[service]',
    DB_GET_ALL_IDEA : 'Unable to getAllIdea[service]',
    DB_GET_MY_IDEA : 'Unable to getMyIdea[service]',
    DB_GET_ADMIN_USER_IDEA : 'Unable to getAdminUserIdea[service]',
    DB_GET_IDEA : 'Unable to getIdea[service]',
    DB_UPDATE_IDEA : 'Unable to updateIdea[service]',
    DB_DELETE_IDEA : 'Unable to deleteIdea[service]',
    //news
    DB_CREATE_NEWS : 'Unable to createNews[service]',
    DB_DELETE_NEWS : 'Unable to  deleteNews[service]',
    //visitor
    DB_FIND_IP : 'Unable to findIp for createIp[service]',
    DB_CREATE_IP : 'Unable to createIp[service]',
    DB_GET_TODAY_VISITOR : 'Unable to getTodayVisitor[service]',
    DB_GET_TOTAL_VISITOR : 'Unable to getTotalVisitor[service]',
    DB_UPDATE_TOTAL_VISITOR : 'Unable to updateTotalVisitor[service]',
    //user
    DB_UPDATE_ROLE : 'Unable to updateRole[service]',
    DB_GET_USER : 'Unable to  getUser[service]',
    DB_LOGOUT : 'Unable to  logout[service]',
    DB_FORCE_LOGOUT : 'Unable to  forceLogout[service]',
    DB_GET_USER_TOKEN : 'Unable to getUserToken[service]',
    DB_UPDATE_USERTOKEN : 'Unable to updateUserToken[service]',
    DB_GET_USER_DATA : 'Unable to getUserData[service]',
}

module.exports = {
    ...preProcessing,
    ...postProcessing,
    ...dbError
}